# Generated by Django 4.1.6 on 2023-02-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoItem',
            new_name='PlanItem',
        ),
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='PlanList',
        ),
    ]
