# Generated by Django 4.1.6 on 2023-02-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_list_app', '0002_rename_todoitem_planitem_rename_todolist_planlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planitem',
            old_name='todo_list',
            new_name='plan_list',
        ),
    ]
