# Generated by Django 4.1.6 on 2023-02-03 20:51

from django.db import migrations, models
import django.db.models.deletion
import planning_list_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_list_app', '0003_rename_todo_list_planitem_plan_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=planning_list_app.models.one_week_hence)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.RenameModel(
            old_name='PlanList',
            new_name='ToDoList',
        ),
        migrations.DeleteModel(
            name='PlanItem',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='todo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning_list_app.todolist'),
        ),
    ]
